# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_yhbXhR7UpX0W1tr5pTor-j1vTJ9VCsu
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv("Advertising_F.csv")

df.head()
df.info()

st.title("Advertising Effectiveness Dashboard (Jahad_Richards)")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X-Axis",["TV","Radio","Newspaper"])#Headers to choose from to measure
y_var=st.sidebar.selectbox("Y-Axis",["sales"])

fig=px.scatter(df,x=x_var,y=y_var,trendline='ols')
st.plotly_chart(fig)#Size , Colors

st.write("### Data Frame")#Show the data frame
st.dataframe(df)

#Lets show map, maps are good
st.title("I'm the Map")
fig=px.scatter_mapbox(df,lat="latitude",lon="longitude",color="sales",size="TV",hover_name="City")
#Publish the map
fig.update_layout(mapbox_style="carto-positron")#StreetView is possible with other codes
st.plotly_chart(fig)
